//CREACIÓN DE TABLA PARENTESCO

CREATE TABLE PARENTESCO (
    PAR_ID SERIAL NOT NULL,
    PAR_DESC_PARENTESCO VARCHAR (15),
    PAR_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (PAR_ID)
);

//INSERTS NECESARIOS PARA LA CREACIÓN DE LA TABLA PARENTESCO

INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('MADRE', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('PADRE', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('HERMANA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('HERMANO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('HIJO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('HIJA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('ABUELO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('ABUELA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('TIO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('TIA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('CUÑADO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('CUÑADA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('YERNO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('NUERA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('SUEGRO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('SUEGRA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('BISABUELO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('BISABUELA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('TATARABUELO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('TATARABUELA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('HERMANASTRO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('HERMANASTRA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('PADRASTRO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('MADRASTRA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('SOBRINA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('SOBRINO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('PRIMO', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('PRIMA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('ESPOSA', 1);
INSERT INTO PARENTESCO (PAR_DESC_PARENTESCO, PAR_SITUACION) VALUES ('ESPOSO', 1);

//CREACIÓN DE TABLA ESTADO_CIVIL

CREATE TABLE ESTADO_CIVIL (
    EST_ID SERIAL NOT NULL,
    EST_DESC_PARENTESCO VARCHAR (15),
    EST_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (EST_ID)
);

//INSERTS NECESARIOS PARA LA CREACIÓN DE LA TABLA ESTADO_CIVIL

INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('SOLTERO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('CASADO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('DIVORCIADO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('VIUDO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('CONCUBINO', 1);


//AGREGAR CAMPOS A LA TABALA TROPA_BENEFICIARIOS

ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_SEXO VARCHAR(1);
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_ESTADO_CIVIL INTEGER;
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_FECHA_NACIMIENTO DATE;
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_DEPTO_NACIMIENTO INTEGER;
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_MUN_NACIMIENTO INTEGER;