//CREACIÓN DE TABLA ESTADO_CIVIL

CREATE TABLE ESTADO_CIVIL (
    EST_ID SERIAL NOT NULL,
    EST_DESC_PARENTESCO VARCHAR (15),
    EST_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (EST_ID)
);

//INSERTS NECESARIOS PARA LA CREACIÓN DE LA TABLA ESTADO_CIVIL

INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('SOLTERO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('CASADO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('DIVORCIADO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('VIUDO', 1);
INSERT INTO ESTADO_CIVIL (EST_DESC_PARENTESCO, EST_SITUACION) VALUES ('CONCUBINO', 1);


//AGREGAR CAMPOS A LA TABLA TROPA_BENEFICIARIOS

ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_SEXO VARCHAR(1);
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_ESTADO_CIVIL INTEGER;
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_FECHA_NACIMIENTO DATE;
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_DEPTO_NACIMIENTO INTEGER;
ALTER TABLE TROPA_BENEFICIARIOS ADD BEN_MUN_NACIMIENTO INTEGER;


//AGREGAR CAMPOS A LA TABLA MPER
ALTER TABLE MPER ADD PER_NOM3 VARCHAR(15);